config/routes.rb
App::Application.routes.draw do

  resources :risks

  resources :emergencies

  resources :teams

  resources :biachecklists

  resources :crises

  resources :plans

  resources :tests

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards

  root :to => 'dashboards#index'

end

app/models/emergency.rb
class Emergency < ActiveRecord::Base
  attr_accessible :ambulance, :electric, :fire, :gas_heat, :hospital, :insurance, :newspaper, :police, :radio, :telephone, :tvchannel
end

app/controllers/emergencies_controller.rb
class EmergenciesController < ApplicationController
  # GET /emergencies
  # GET /emergencies.json
  def index
    @emergencies = Emergency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @emergencies }
    end
  end

  # GET /emergencies/1
  # GET /emergencies/1.json
  def show
    @emergency = Emergency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @emergency }
       format.pdf do
        pdf = EmergenciesPdf.new(@emergency)
        send_data pdf.render , filename: "#{@emergency.police}.pdf", type: "application/pdf" , disposition: "inline"
      end
    end
  end

  # GET /emergencies/new
  # GET /emergencies/new.json
  def new
    @emergency = Emergency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @emergency }
    end
  end

  # GET /emergencies/1/edit
  def edit
    @emergency = Emergency.find(params[:id])
  end

  # POST /emergencies
  # POST /emergencies.json
  def create
    @emergency = Emergency.new(params[:emergency])

    respond_to do |format|
      if @emergency.save
        format.html { redirect_to @emergency, notice: 'Emergency was successfully created.' }
        format.json { render json: @emergency, status: :created, location: @emergency }
      else
        format.html { render action: "new" }
        format.json { render json: @emergency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /emergencies/1
  # PUT /emergencies/1.json
  def update
    @emergency = Emergency.find(params[:id])

    respond_to do |format|
      if @emergency.update_attributes(params[:emergency])
        format.html { redirect_to @emergency, notice: 'Emergency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @emergency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emergencies/1
  # DELETE /emergencies/1.json
  def destroy
    @emergency = Emergency.find(params[:id])
    @emergency.destroy

    respond_to do |format|
      format.html { redirect_to emergencies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/emergencies_helper.rb
module EmergenciesHelper
end

app/views/emergencies/_form.html.erb
<html>
<head>
  <script>
  $(function() {
     $( "#datepicker" ).datepicker({
      showOn: "button",
      buttonImage: "/images/calendar.jpg",
      buttonImageOnly: true
    });
  });
  </script>
</head>
<body>
  <%= form_for(@emergency) do |f| %>
  <% if @emergency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emergency.errors.count, "error") %> prohibited this emergency from being saved:</h2>

      <ul>
      <% @emergency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="span11 offset well">
  <div class="form-horizontal">
    <div class="accordion " id="accordion2">
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
            New Contact
          </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse in">
          <div class="accordion-inner">
            <div class="field">
              <%= f.label :police_station %><br />
              <%= f.text_field :police %>
            </div>
            <div class="field">
              <%= f.label :fire_station %><br />
              <%= f.text_field :fire %>
            </div>
            <div class="field">
              <%= f.label :ambulance %><br />
              <%= f.text_field :ambulance %>
            </div>
            <div class="field">
              <%= f.label :hospital %><br />
              <%= f.text_field :hospital %>
            </div>
            <div class="field">
              <%= f.label :insurance %><br />
              <%= f.text_field :insurance %>
            </div>
            <div class="field">
              <%= f.label :telephone %><br />
              <%= f.text_field :telephone %>
            </div>
            <div class="field">
              <%= f.label :gas_or_heat_Dept %><br />
              <%= f.text_field :gas_heat %>
            </div>
            <div class="field">
              <%= f.label :electric_dept %><br />
              <%= f.text_field :electric %>
            </div>
            <div class="field">
              <%= f.label :newspaper %><br />
              <%= f.text_field :newspaper %>
            </div>
            <div class="field">
              <%= f.label :radio_channel %><br />
              <%= f.text_field :radio %>
            </div>
            <div class="field">
              <%= f.label :tvchannel %><br />
              <%= f.text_field :tvchannel %>
            </div>
            </div>
            </div>
           </div>  
      <!-- <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsethree">
            Document Control
          </a>
        </div>
        <div id="collapsethree" class="accordion-body collapse">
          <div class="accordion-inner">
            <div class="control-group">
              <b> Document Title </b><br/>
              
            </div>
            <div class="control-group">
              <b> Attachment </b><br/>
              <%= f.file_field :attach %>
            </div>
          </div>
        </div>
      </div> -->
     <!--  <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsefour">
            Governance Risk and Compliance
          </a>
        </div>
        <div id="collapsefour" class="accordion-body collapse">
          <div class="accordion-inner">
            <p>Governance Risk and Compliance</p>
          </div>
        </div>
      </div> -->
   <!--    <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsefive">
            Approval , Review and  Distribution
          </a>
        </div>
        <div id="collapsefive" class="accordion-body collapse">
          <div class="accordion-inner">
            <p>Approval , Review and  Distribution</p>
          </div>
        </div>
      </div> -->
    </div>
  </div>
  <br>
  <div class="actions">
    <%= f.submit '+ Add New Emergency contact', :class =>  "pure-button pure-button-primary"%>
    <%= link_to 'Cancel', emergencies_path , :class => "pure-button pure-button-primary"%>
  </div>
<% end %>
</div>
</body>
</html>

app/views/emergencies/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
		<div><img src="/images/fixnix.png"></div>
	</div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well"> 
				<h1>Editing Contacts</h1>

				<%= render 'form' %>
			</div>
		</div>
	</div>

<%= link_to 'Show', @emergency %> |
<%= link_to 'Back', emergencies_path %>

</body>
</html>

app/views/emergencies/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#Policy" data-toggle="tab">Emergency Contact Details</a></li>
                        <!-- <li><a href="#EP" data-toggle="tab">Existing Risks</a></li> -->
                    </ul>
                    <div class="tab-content">
                        <div id="Policy" class="tab-pane active">
                            <table class="table table-bordered">
                            <tr>
                                <th>Police Station</th>
                                <th>Fire Station</th>
                                <th>Ambulance</th>
                                <th>Hospital</th>
                                <!-- <th>Insurance</th>
                                <th>Telephone</th>
                                <th>Gas heat</th>
                                <th>Electric</th>
                                <th>Newspaper</th>
                                <th>Radio</th>
                                <th>Tvchannel</th> -->                               
                              </tr>

                            <% @emergencies.each do |emergency| %>
                              <tr>
                                <td><%= emergency.police %></td>
                                <td><%= emergency.fire %></td>
                                <td><%= emergency.ambulance %></td>
                                <td><%= emergency.hospital %></td>
                                <!-- <td><%= emergency.insurance %></td>
                                <td><%= emergency.telephone %></td>
                                <td><%= emergency.gas_heat %></td>
                                <td><%= emergency.electric %></td>
                                <td><%= emergency.newspaper %></td>
                                <td><%= emergency.radio %></td>
                                <td><%= emergency.tvchannel %></td> -->
                                <td><%= link_to 'Show', emergency %></td>
                                <td><%= link_to 'Edit', edit_emergency_path(emergency) %></td>
                                <td><%= link_to 'Destroy', emergency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                              </tr>
                            <% end %>
                            </table>
                            <br />

                         <%= link_to '+ Add New Emergency Contact', new_emergency_path , :class => "pure-button pure-button-primary" %>
                            </div>
                         <div id="EP" class="tab-pane">
                        <h4>Existing Risks</h4>
                        <p> Coming Soon ...</p>
                    </div>
                </div><!-- /.tab-content -->
            </div><!-- /.tabbable -->
        </div>
    </div>
</div>
<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/emergencies/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
		<div><img src="/images/fixnix.png"></div>
	</div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">

			<%= render 'form' %>
			<br>

		</div>
	</div>
	<!-- <div id="footer">Footer</div> -->
</body>
</html>

<%= link_to 'Back', emergencies_path %>

app/views/emergencies/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">
      <p id="notice"><%= notice %></p>

<p>
  <b>Police Station:</b>
  <%= @emergency.police %>
</p>

<p>
  <b>Fire Station:</b>
  <%= @emergency.fire %>
</p>

<p>
  <b>Ambulance:</b>
  <%= @emergency.ambulance %>
</p>

<p>
  <b>Hospital:</b>
  <%= @emergency.hospital %>
</p>

<p>
  <b>Insurance:</b>
  <%= @emergency.insurance %>
</p>

<p>
  <b>Telephone:</b>
  <%= @emergency.telephone %>
</p>

<p>
  <b>Gas heat:</b>
  <%= @emergency.gas_heat %>
</p>

<p>
  <b>Electric:</b>
  <%= @emergency.electric %>
</p>

<p>
  <b>Newspaper:</b>
  <%= @emergency.newspaper %>
</p>

<p>
  <b>Radio:</b>
  <%= @emergency.radio %>
</p>

<p>
  <b>Tvchannel:</b>
  <%= @emergency.tvchannel %>
</p>


<%= link_to "Create Report", emergency_path(@emergency, :format => "pdf") , :class => "pure-button pure-button-primary"  %>       
<%= link_to 'Edit', edit_emergency_path(@emergency), :class => "pure-button pure-button-primary" %> 
<%= link_to 'Back', emergencies_path , :class => "pure-button pure-button-primary" %>

   </div>
   <!--   <div id="footer">Footer</div> -->

 </body>
 </html>