config/routes.rb
App::Application.routes.draw do

  resources :risks

  resources :emergencies

  resources :teams

  resources :biachecklists

  resources :crises

  resources :plans

  resources :tests

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards

  root :to => 'dashboards#index'

end

app/models/risk.rb
class Risk < ActiveRecord::Base
  attr_accessible :consequence_current, :consequence_target, :likelihood_current, 
  :likelihood_target, :risk, :risk_id, :risk_level
end

app/controllers/risks_controller.rb
class RisksController < ApplicationController
  # GET /risks
  # GET /risks.json
  def index
    @risks = Risk.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @risks }
    end
  end

  # GET /risks/1
  # GET /risks/1.json
  def show
    @risk = Risk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @risk }
      format.pdf do
        pdf = RisksPdf.new(@risk)
        send_data pdf.render , filename: "#{@risk.risk_id}.pdf", type: "application/pdf" , disposition: "inline"
      end
     
    end
  end

  # GET /risks/new
  # GET /risks/new.json
  def new
    @risk = Risk.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @risk }
    end
  end

  # GET /risks/1/edit
  def edit
    @risk = Risk.find(params[:id])
  end

  # POST /risks
  # POST /risks.json
  def create
    @risk = Risk.new(params[:risk])

    respond_to do |format|
      if @risk.save
        format.html { redirect_to @risk, notice: 'Risk was successfully created.' }
        format.json { render json: @risk, status: :created, location: @risk }
      else
        format.html { render action: "new" }
        format.json { render json: @risk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /risks/1
  # PUT /risks/1.json
  def update
    @risk = Risk.find(params[:id])

    respond_to do |format|
      if @risk.update_attributes(params[:risk])
        format.html { redirect_to @risk, notice: 'Risk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @risk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /risks/1
  # DELETE /risks/1.json
  def destroy
    @risk = Risk.find(params[:id])
    @risk.destroy

    respond_to do |format|
      format.html { redirect_to risks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/risks_helper.rb
module RisksHelper
end

app/views/risks/_form.html.erb
<html>
<head>
  <script>
  $(function() {
     $( "#datepicker" ).datepicker({
      showOn: "button",
      buttonImage: "/images/calendar.jpg",
      buttonImageOnly: true
    });
  });
  </script>
</head>
<body>
  <%= form_for(@risk) do |f| %>
  <% if @risk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@risk.errors.count, "error") %> prohibited this risk from being saved:</h2>

      <ul>
      <% @risk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="span11 offset well">
  <div class="form-horizontal">
    <div class="accordion " id="accordion2">
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
            New Risk
          </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse in">
          <div class="accordion-inner">
  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :risk_id %>
  </div>
  <div class="field">
    <%= f.label :risk_by %><br />
    <%= f.select :risk, [[' ',' '],['Loss of IT',''],
        ['Building',''],['Staff','Staff'],['Cyber Attack','Cyber Attack'],['Earthquake','Earthquake'],['Fire','Fire'],
        ['Terroist Attack','Terroist Attack'],['Forest Fire','Forest Fire'], ['Flood','Flood'],
        ['Tornado','Tornado']] %>
  </div>
  <div class="field">
    <%= f.label :consequence_current %><br />
    <%= f.select :consequence_current, [[' ',' '],['Insignificant','Insignificant'],
        ['Minor','Minor'],['Moderate','Moderate'],['Major','Major'],['Catastropic','Catastropic']] %>
  </div>
  <div class="field">
    <%= f.label :consequence_target %><br />
    <%= f.select :consequence_target, [[' ',' '],['Insignificant','Insignificant'],
        ['Minor','Minor'],['Moderate','Moderate'],['Major','Major'],['Catastropic','Catastropic']] %>
  </div>
  <div class="field">
    <%= f.label :likelihood_current %><br />
    <%= f.select :likelihood_current, [[' ',' '],['Moderate','Moderate'],['Rare','Rare'],
                 ['Unlikely','Unlikely']] %>
  </div>
  <div class="field">
    <%= f.label :likelihood_target %><br />
    <%= f.select :likelihood_target, [[' ',' '],['Moderate','Moderate'],['Rare','Rare'],
                 ['Unlikely','Unlikely']] %>
  </div>
  <div class="field">
    <%= f.label :risk_level %><br />
    <%= f.select :risk_level, [[' ',' '],['Extreme','Extreme'],['High','High'],
                 ['Low','Low']] %>
  </div>
 </div>
        </div>
      </div>      
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsethree">
            Document Control
          </a>
        </div>
        <div id="collapsethree" class="accordion-body collapse">
          <div class="accordion-inner">
            <div class="control-group">
              <b> Document Title </b><br/>
              
            </div>
            <div class="control-group">
              <b> Attachment </b><br/>
              <%= f.file_field :attach %>
            </div>
          </div>
        </div>
      </div>
     <!--  <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsefour">
            Governance Risk and Compliance
          </a>
        </div>
        <div id="collapsefour" class="accordion-body collapse">
          <div class="accordion-inner">
            <p>Governance Risk and Compliance</p>
          </div>
        </div>
      </div> -->
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsefive">
            Approval , Review and  Distribution
          </a>
        </div>
        <div id="collapsefive" class="accordion-body collapse">
          <div class="accordion-inner">
            <p>Approval , Review and  Distribution</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
   <div class="actions">
    <%= f.submit '+ Add New Risk', :class =>  "pure-button pure-button-primary"%>
    <%= link_to 'Cancel', risks_path , :class => "pure-button pure-button-primary"%>
  </div>
<% end %>
</div>
</body>
</html>

app/views/risks/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
		<div><img src="/images/fixnix.png"></div>
	</div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well"> 
				<h1>Editing Risk</h1>

				<%= render 'form' %>
			</div>
		</div>
	</div>
	<!-- 	<div id="footer">Footer</div> -->

<%= link_to 'Show', @risk %> |
<%= link_to 'Back', risks_path %>

</body>
</html>

app/views/risks/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#Policy" data-toggle="tab">Risks</a></li>
                        <!-- <li><a href="#EP" data-toggle="tab">Existing Risks</a></li> -->
                    </ul>
                    <div class="tab-content">
                        <div id="Policy" class="tab-pane active">
                            <table class="table table-bordered">
                               <tr>
                                <th>ID</th>
                                <th>Risk By</th>
                               <!--  <th>Consequence current</th>
                                <th>Consequence target</th>
                                <th>Likelihood current</th>
                                <th>Likelihood target</th> -->
                                <th>Risk level</th>
                              </tr>

                            <% @risks.each do |risk| %>
                              <tr>
                                <td><%= risk.risk_id %></td>
                                <td><%= risk.risk %></td>
                                <!-- <td><%= risk.consequence_current %></td>
                                <td><%= risk.consequence_target %></td>
                                <td><%= risk.likelihood_current %></td>
                                <td><%= risk.likelihood_target %></td> -->
                                <td><%= risk.risk_level %></td>
                                <td><%= link_to 'Show', risk %></td>
                                <td><%= link_to 'Edit', edit_risk_path(risk) %></td>
                                <td><%= link_to 'Destroy', risk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                              </tr>
                            <% end %>
                                                        </table>

                            <br />

                            <%= link_to '+ Add New Risk', new_risk_path , :class => "pure-button pure-button-primary" %>
                            </div>
                         <div id="EP" class="tab-pane">
                        <h4>Existing Risks</h4>
                        <p> Coming Soon ...</p>
                    </div>
                </div><!-- /.tab-content -->
            </div><!-- /.tabbable -->
        </div>
    </div>
</div>
<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/risks/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
		<div><img src="/images/fixnix.png"></div>
	</div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">

			<%= render 'form' %>
			<br>

		</div>
	</div>
	<!-- <div id="footer">Footer</div> -->
</body>
</html>

<%= link_to 'Back', risks_path %>

app/views/risks/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">
      <p id="notice"><%= notice %></p>

<p>
  <b>Risk:</b>
  <%= @risk.risk_id %>
</p>

<p>
  <b>Risk:</b>
  <%= @risk.risk %>
</p>

<p>
  <b>Consequence current:</b>
  <%= @risk.consequence_current %>
</p>

<p>
  <b>Consequence target:</b>
  <%= @risk.consequence_target %>
</p>

<p>
  <b>Likelihood current:</b>
  <%= @risk.likelihood_current %>
</p>

<p>
  <b>Likelihood target:</b>
  <%= @risk.likelihood_target %>
</p>

<p>
  <b>Risk level:</b>
  <%= @risk.risk_level %>
</p>


<%= link_to "Create Report", risk_path(@risk, :format => "pdf") , :class => "pure-button pure-button-primary"  %>       
<%= link_to 'Edit', edit_risk_path(@risk), :class => "pure-button pure-button-primary" %> 
<%= link_to 'Back', risks_path , :class => "pure-button pure-button-primary" %>

   </div>
   <!--   <div id="footer">Footer</div> -->

 </body>
 </html>