config/routes.rb
App::Application.routes.draw do

  resources :risks

  resources :emergencies

  resources :teams

  resources :biachecklists

  resources :crises

  resources :plans

  resources :tests

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards

  root :to => 'dashboards#index'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  attr_accessible :auditmetric, :emergencyresponse, :launchcriteria, :losstype, :plan_objective, 
  :plan_title, :planstatus, :recoverableplantype, :recoverableresponse, :responsible, :review, :sponsor, 
  :sucesscriteria
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plan }
      format.pdf do
        pdf = PlansPdf.new(@plan)
        send_data pdf.render , filename: "#{@plan.plan_title}.pdf", type: "application/pdf" , disposition: "inline"
      end
    end
  end

  # GET /plans/new
  # GET /plans/new.json
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render json: @plan, status: :created, location: @plan }
      else
        format.html { render action: "new" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.json
  def update
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<html>
<head>
  <script>
  $(function() {
     $( "#datepicker" ).datepicker({
      showOn: "button",
      buttonImage: "/images/calendar.jpg",
      buttonImageOnly: true
    });
  });
  </script>
</head>
<body>
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="span11 offset well">
  <div class="form-horizontal">
    <div class="accordion " id="accordion2">
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
            New Plan
          </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse in">
          <div class="accordion-inner">
  <div class="field">
    <%= f.label :plan_title %><br />
      Give the plan a title, name or code so it's easily identified on the plan list menu<br />
    <%= f.text_field :plan_title %>
  </div>
  
  <div class="field">
    <%= f.label :plan_sponsor %><br />
    Who is responsible for keeping this plan realitistic, communicateed and applicable? (quite a job, right?)<br />
    <%= f.text_field :sponsor %>
  </div>
  <div class="field">
    <%= f.label :launch_responsible %><br />
    There should be someone who is authorized to lunch this plan (sometimes the Plan Sponsor)<br />
    <%= f.text_field :responsible %>
  </div>
  <div class="field">
    <%= f.label :recoverable_response %><br />
    <%= f.text_field :recoverableresponse %>
  </div>
  <div class="field">
    <%= f.label :plan_status %><br />
    Describe the status of the plan. Only productive plans are considered "live" plans!<br />
    <%= f.select :planstatus, [[' ',' '],['Proposed','Proposed'],['Design','Design'],
    ['Transition','Transition'],['Production','Production'],['Retired','Retired']] %>
  </div>
  <div class="field">
    <%= f.label :recoverable_plan_type %><br />
    <%= f.text_field :recoverableplantype %>
  </div>
  <div class="field">
    <%= f.label :losstype %><br />
    <%= f.text_field :losstype %>
  </div>
  <div class="field">
    <%= f.label :emergency_response %><br />
    <%= f.text_field :emergencyresponse %>
  </div>
  <div class="field">
    <%= f.label :review_date%><br />
    <%= f.text_field :review, :id=> :datepicker %>
  </div>
 
 </div>
  </div>
 </div>  

 <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsefour">
            Objective & Criteria
          </a>
        </div>
        <div id="collapsefour" class="accordion-body collapse">
          <div class="accordion-inner">
            <div class="field">
             <%= f.label :plan_objective %><br>
             Describe the plan objective, it should be something short and straightforward to understand.<br />
            <%= f.text_area :plan_objective %>
         </div>
         <div class="field">
            <%= f.label :audit_metric %><br />
            Continuity plans without regular testing and audits are doomed to fail. Set your audit metric criteria (Response time?, etc)<br />
            <%= f.text_area :auditmetric %>
        </div>
        <div class="field">
          <%= f.label :sucess_criteria %><br />
          Define a success criteria for the metric you have just defined (Under 2 hs, etc)<br />
          <%= f.text_area :sucesscriteria %>
       </div>
        <div class="field">
          <%= f.label :launch_criteria %><br />
         Describe the criteria the plan responsible should use to know if it's appropiate to kick the plan or not in the case of an emergency.<br />
         <%= f.text_area :launchcriteria %>
         </div>
          </div>
        </div>
      </div>    
      <!-- <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsethree">
            Document Control
          </a>
        </div>
        <div id="collapsethree" class="accordion-body collapse">
          <div class="accordion-inner">
            <div class="control-group">
              <b> Document Title </b><br/>
              
            </div>
            <div class="control-group">
              <b> Attachment </b><br/>
              <%= f.file_field :attach %>
            </div>
          </div>
        </div>
      </div>
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsefour">
            Governance Risk and Compliance
          </a>
        </div>
        <div id="collapsefour" class="accordion-body collapse">
          <div class="accordion-inner">
            <p>Governance Risk and Compliance</p>
          </div>
        </div>
      </div> -->
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsefive">
            Approval , Review and  Distribution
          </a>
        </div>
        <div id="collapsefive" class="accordion-body collapse">
          <div class="accordion-inner">
            <p>Approval , Review and  Distribution</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
   <div class="actions">
    <%= f.submit '+ Add New BCM Plan', :class =>  "pure-button pure-button-primary"%>
    <%= link_to 'Cancel', plans_path , :class => "pure-button pure-button-primary"%>
  </div>
<% end %>
</div>
</body>
</html>

app/views/plans/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
		<div><img src="/images/fixnix.png"></div>
	</div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well"> 
				<h1>Editing Plan</h1>

				<%= render 'form' %>
			</div>
		</div>
	</div>
	<!-- 	<div id="footer">Footer</div> -->

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

</body>
</html>

app/views/plans/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#Policy" data-toggle="tab">Plan</a></li>
                        <!-- <li><a href="#EP" data-toggle="tab">Existing Plans</a></li> -->
                    </ul>
                    <div class="tab-content">
                        <div id="Policy" class="tab-pane active">
                            <table class="table table-bordered">
                            <tr>
                                <th>Plan title</th>
                                <th>Plan objective</th>
                                <!-- <th>Auditmetric</th>
                                <th>Sucesscriteria</th>
                                <th>Launchcriteria</th>
                                <th>Sponsor</th> -->
                                <th>Responsible</th>
                                <!-- <th>Recoverable response</th> -->
                                <th>Plan status</th>
                               <!--  <th>Recoverableplantype</th>
                                <th>Losstype</th>
                                <th>Emergencyresponse</th> -->
                                <th>Review Date</th>
                              </tr>

                            <% @plans.each do |plan| %>
                              <tr>
                                <td><%= plan.plan_title %></td>
                                <td><%= plan.plan_objective %></td>
                                <!-- <td><%= plan.auditmetric %></td>
                                <td><%= plan.sucesscriteria %></td>
                                <td><%= plan.launchcriteria %></td>
                                <td><%= plan.sponsor %></td> -->
                                <td><%= plan.responsible %></td>
                                <!-- <td><%= plan.recoverableresponse %></td> -->
                                <td><%= plan.planstatus %></td>
                                <!-- <td><%= plan.recoverableplantype %></td>
                                <td><%= plan.losstype %></td>
                                <td><%= plan.emergencyresponse %></td> -->
                                <td><%= plan.review %></td>
                                <td><%= link_to 'Show', plan %></td>
                                <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
                                <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                              </tr>
                            <% end %>
                            </table>
                            <br />
                                  <%= link_to '+ Add New Plan', new_plan_path , :class => "pure-button pure-button-primary" %>
                            </div>
                         <div id="EP" class="tab-pane">
                        <h4>Existing Plans</h4>
                        <p> Coming Soon ...</p>
                    </div>
                </div><!-- /.tab-content -->
            </div><!-- /.tabbable -->
        </div>
    </div>
</div>
<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/plans/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
		<div><img src="/images/fixnix.png"></div>
	</div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">

			<%= render 'form' %>
			<br>

		</div>
	</div>
	<!-- <div id="footer">Footer</div> -->
</body>
</html>


<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">
      <p id="notice"><%= notice %></p>

<p>
  <b>Plan title:</b>
  <%= @plan.plan_title %>
</p>

<p>
  <b>Plan objective:</b>
  <%= @plan.plan_objective %>
</p>

<p>
  <b>Auditmetric:</b>
  <%= @plan.auditmetric %>
</p>

<p>
  <b>Sucesscriteria:</b>
  <%= @plan.sucesscriteria %>
</p>

<p>
  <b>Launchcriteria:</b>
  <%= @plan.launchcriteria %>
</p>

<p>
  <b>Sponsor:</b>
  <%= @plan.sponsor %>
</p>

<p>
  <b>Responsible:</b>
  <%= @plan.responsible %>
</p>

<p>
  <b>Recoverableresponse:</b>
  <%= @plan.recoverableresponse %>
</p>

<p>
  <b>Planstatus:</b>
  <%= @plan.planstatus %>
</p>

<p>
  <b>Recoverableplantype:</b>
  <%= @plan.recoverableplantype %>
</p>

<p>
  <b>Losstype:</b>
  <%= @plan.losstype %>
</p>

<p>
  <b>Emergencyresponse:</b>
  <%= @plan.emergencyresponse %>
</p>

<p>
  <b>Review:</b>
  <%= @plan.review %>
</p>

<%= link_to "Create Report", plan_path(@plan, :format => "pdf") , :class => "pure-button pure-button-primary"  %>       
<%= link_to 'Edit', edit_plan_path(@plan), :class => "pure-button pure-button-primary" %> 
<%= link_to 'Back', plans_path , :class => "pure-button pure-button-primary" %>

   </div>
   <!--   <div id="footer">Footer</div> -->

 </body>
 </html>